version: '3.8'
services:
  database:
    image: mysql:5.7
    container_name: arent_test_db
    restart: always
    environment:
      - MYSQL_DATABASE=health_app_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3306:3306'
    command:
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
